### ISSUE TITLE
tflint fails to find modules

### ISSUE THREAD

**Issue by jakelevinez** [terraform-linters/tflint-bundle#32]
running on gitlab it appears tflint has trouble finding some modules, inconsistently.  I have checked gitlab cache and also tried changing from latest image to last.  Not sure what more I can do to help figure out what is going on.  Other tf steps in the same pipeline do not complain about modules not being loaded.

Issue has started in the last few weeks or so.

**Comment by wata727** [comment]
Please tell us in detail about the expected behavior and the actual behavior. In addition, having minimal reproducible code and settings will help identify the problem.

The version released in the last few weeks is v0.37.0, but the code related to module discovery should not have changed.
